### PR TITLE
Blog Posting Application: PR# 2

### PR DESCRIPTION
**Pull request by Ayush604141**
[**DBMS**](https://www.loom.com/share/03ec2144212a4837a212e419413157d3)
_Milestone 2 and Milestone 3_
- Showcased the relational data model with normalization.
- Showcased DDL commands.

[**OOPs**](https://www.loom.com/share/dc0f9c0a84504f02a6c622d9b99b4c6a)
_Milestone 2_
- Showcased the this pointer.
- Showcased the dynamic memory allocation.

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Hey @Ayush604141 ,
For DDL, we need you to explain every tables, attributes along with their keys and constraints. But you missed to cover everything.
And about executing queries, we need you to showcase the change in the database and tables on each query execution one by one. But you didn't show that.

Please make a video with all the necessary things mentioned above.

For Normalization,
Your explanation is not correct and not sufficient to close the Milestone.
First focus on DDL, and try to submit at today EOD. 
Then focus on normalization.

**Comment by Ayush604141** [comment]
> Hey @Ayush604141 , For DDL, we need you to explain every tables, attributes along with their keys and constraints. But you missed to cover everything. And about executing queries, we need you to showcase the change in the database and tables on each query execution one by one. But you didn't show that.
> 
> Please make a video with all the necessary things mentioned above.
> 
> For Normalization, Your explanation is not correct and not sufficient to close the Milestone. First focus on DDL, and try to submit at today EOD. Then focus on normalization.

Hey @PRASANNAPATHI, I have updated the video link in PR description as well as kalvium.community. You can have a look.

**Comment by Kalvium-Program** [comment]
Hey @Ayush604141 , 

Tables explanation are fine,

what about the execution? That I mentioned in the previous comment

"And about executing queries, we need you to showcase the change in the database and tables on each query execution one by one. But you didn't show that."

Please add a video for that, also make sure you not just run the queries, you should show the changes in the tables and database, for each queries.  you can use show tables, describe table commands.

**Comment by PRASANNAPATHI** [comment]
Hey @Ayush604141 ,

Tables explanation are fine,

what about the execution? That I mentioned in the previous comment

"And about executing queries, we need you to showcase the change in the database and tables on each query execution one by one. But you didn't show that."

Please add a video for that, also make sure you not just run the queries, you should show the changes in the tables and database, for each queries. you can use show tables, describe table commands.

**Comment by Tharun-kailash** [comment]
Hey Ayush, 
The code looks good but you didn't explain the concepts very clearly. Try to give a detailed explanation what a concept is, where and how it is used and relate the concept with your code. A running demo would be appreciated. 

You can go ahead and merge this PR!
Thanks.

**Comment by Ayush604141** [comment]
> Hey Ayush, The code looks good but you didn't explain the concepts very clearly. Try to give a detailed explanation what a concept is, where and how it is used and relate the concept with your code. A running demo would be appreciated.
> 
> You can go ahead and merge this PR! Thanks.

Hey Tharun, I did explain the code and I don't think that I can do it any better. But for the sake of clarity we can have a viva meeting for the same. This way, I will be more clear to explain what you want to know and you verify if I applied the learned concepts in a proper manner.

**Comment by PRASANNAPATHI** [comment]
For Relational Data Model and Normalization:
Your explanation is not fully satisfactory. And there are some mistakes in your explanation.
Without 2nd normal form, the 3rd normal form cannot be done. Also 1st normal form- main thing is single valued attribute- missing in your explanatio.

Please make another video, where you explain all the normal forms & their rules & functions.
And then explain whatever rules applicable/applied in your project.

**Comment by Tharun-kailash** [comment]
> > Hey Ayush, The code looks good but you didn't explain the concepts very clearly. Try to give a detailed explanation what a concept is, where and how it is used and relate the concept with your code. A running demo would be appreciated.
> > You can go ahead and merge this PR! Thanks.
> 
> Hey Tharun, I did explain the code and I don't think that I can do it any better. But for the sake of clarity we can have a viva meeting for the same. This way, I will be more clear to explain what you want to know and you verify if I applied the learned concepts in a proper manner.

I would like you to schedule a viva slot in my calendar. I'm looking forward to a more in-depth discussion of this PR and hearing your explanations of the concepts involved.
Thanks

**Comment by th3c0d3br34ker** [comment]
Concepts: `This pointer` and `Dynamic memory allocation`.
Approved during viva [for OOP].

**Review by th3c0d3br34ker — APPROVED** [review]

**Comment by PRASANNAPATHI** [comment]
DDL is approved.

Please merge it for DDL.(DBMS)

**Pull request merged**
